gems:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-sitemap

paginate: 20
paginate_path: /news/:num
permalink: /:title

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

exclude:
  - css/styles.css
  - Gemfile
